// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.Data;

#nullable disable

namespace ToDoList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240201152855_ScndMigration")]
    partial class ScndMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoList.Models.TaskToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StatutTask")
                        .HasColumnType("bit");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TasksToDo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Faut ranger",
                            StatutTask = false,
                            Title = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laver la chambre des enfants",
                            StatutTask = false,
                            Title = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Faire à manger",
                            StatutTask = false,
                            Title = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Promener les chiens",
                            StatutTask = false,
                            Title = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Visio avec l'équipe à 20h00",
                            StatutTask = false,
                            Title = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
